### ISSUE TITLE
For someone looking for an actively maintained fork

### ISSUE THREAD

**Issue by rockyzhang24** [nvim-treesitter/nvim-treesitter-context#109]
This repo has been unmaintained for a while. Many issues and PRs left here for solving the serious defects, and no response and merge. If you're still using this plugin, you can divert to @lewis6991 's forked repo (https://github.com/lewis6991/nvim-treesitter-context). He is very responsive and many underlying issues has been solved already there. 

Thanks.

**Comment by romgrk** [comment]
@lewis6991 I'm back on github after some time of absence, do you want to keep maintaining the repo?

We have a few options:
 - I merge your master and give you access here.
 - We keep your fork as the active one. We can ask github to make it the head so it's clear that it's the good one.

Please advise, I'll wait for you answer before touching the code.

**Comment by lewis6991** [comment]
I think I'd prefer to make mine the head if that's possible. Another option is to create a new org.

**Comment by romgrk** [comment]
How about we try to put it under the https://github.com/nvim-treesitter org?

cc @vigoux, @stsewd, @theHamsta, @kyazdani42: can one of you let us know if it's doable to add this plugin to the nvim-treesitter organization?

**Comment by romgrk** [comment]
@lewis6991 as for which one of the forks to transfer, can you share the traffic on your repo? See the `Insights` tab in your repo. This will inform us which of them has more users to minimize disturbance to existing users

![image](https://user-images.githubusercontent.com/1423607/167568488-a71b1a04-d44e-467b-93a1-5e27611f92c8.png)

**Comment by lewis6991** [comment]
![Screenshot_20220510-080807.png](https://user-images.githubusercontent.com/7904185/167568949-fa6bf309-06f1-4f0b-b82a-fe06fe5fe732.png)

**Comment by lewis6991** [comment]
> How about we try to put it under the https://github.com/nvim-treesitter org?
> 
> cc @vigoux, @stsewd, @theHamsta, @kyazdani42: can one of you let us know if it's doable to add this plugin to the nvim-treesitter organization?

Good idea. 

@clason

**Comment by romgrk** [comment]
Alright, so I propose that:
 - We keep this repo as the head of its network, due to its higher usage
 - Merge your master in this repo
 - Transfer the repo to the nvim-treesitter org

Also it might have been unclear but I still plan to help maintain the plugin, but I'd be happy to share the responsability and more importantly the access to avoid repeating the dead repo situation.

**Comment by romgrk** [comment]
According to [the docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), the collaborators on this repo will be transferred with the repo transfer. I've added @lewis6991 so that part is good. All I need is permission to create public repos on the nvim-treesitter org, so I'll wait until someone gives me access to transfer.

Meanwhile, @lewis6991 do you want to open a PR from your master to this master? Please list the PR & issue numbers that you know are fixed, so we can cleanup the PR:s and issues here.

**Comment by lewis6991** [comment]
Good plan.

Good to know your back too 🙂

Sure I'll raise a PR.

**Comment by lewis6991** [comment]
#115

**Comment by romgrk** [comment]
Transfer completed, this can be closed.
