### ISSUE TITLE
#make-range! support

### ISSUE THREAD

**Issue by superzanti** [nvim-treesitter/nvim-treesitter-context#454]
I'm trying to figure out how to match the highlighted portion of the following tree:

![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/4262089/d06cbfbe-fb14-4403-89e5-407da1630da8)

For the following simple code:

![image](https://github.com/nvim-treesitter/nvim-treesitter-context/assets/4262089/e91b8233-d6bd-42ca-805d-057647a32e56)

The make range command would seem to support this and it would be nice to see it in nvim-treesitter-context. However, if there is another way to make this work, please let me know.

**Comment by lewis6991** [comment]
Languages are community maintained and this repo does not track requests. PR's will be accepted.

**Comment by superzanti** [comment]
I may work on this

Reference of the make range function:
https://github.com/nvim-treesitter/nvim-treesitter/blob/caf275382f91ec8a2498d455c4d7d3fd0265ebd3/lua/nvim-treesitter/query.lua#L278

**Comment by pidgeon777** [comment]
Hello @superzanti,

I am writing regarding two matters:

1. I would like to kindly ask if there are any updates regarding your work on the `make-request` function implementation.

2. Additionally, I would value your feedback on my observation regarding the `context.scm` file differences, which I documented in this comment:

[Context.scm comparison feedback](https://github.com/nvim-treesitter/nvim-treesitter-context/commit/718c4089330201c0dcaef56035e78f1a6c965e7a#commitcomment-148523742)

Thank you for your time.

Best regards

**Comment by superzanti** [comment]
1) No, work got busy, and the solution I have is good enough for my needs. I likely won't be working on it.

2) I made my comments in the other thread.

**Comment by pinbraerts** [comment]
So, I looked at iterating through match implementation and concluded that it would require a complete rewrite of the `nvim-treesitter-context` query iteration, or even the entire querying process, using `nvim-treesitter` helpers, or without them (custom `#make-range!` implementation).

On the `nvim-treesitter` side, there are some disadvantages:

1. Unsupported parameters of the `query:iter_match` which are used for optimization here.
2. The resulting iterator of match queries does not have the same format as `query:iter_match`.
3. [Metadata](https://github.com/nvim-treesitter/nvim-treesitter/blob/306dd6e9dc806db1d79568d26e1c9b6c98b95fbc/lua/nvim-treesitter/fold.lua#L47) in the resulting elements must be checked.
4. Unnecessary nesting `@context.start -> {context={start={node={:range}}}}` instead of `{['context.start']={node={:range}}}`.

To support `#make-range!` (and possibly `#set!`) without `nvim-treesitter.query`, one could introduce a preprocessing step through the matches.

1) Replace capture IDs on `#set!`
2) Maybe construct virtual matches and nodes for `#make-range!` (just Lua objects with `:range`)
3) Rewrite the context part to take `range (whole context) + range (thumbnail)` instead of `node (whole context) + range (thumbnail)`.
4) Or somehow make the virtual node the parent node.

Each path seems like a mess. The `nvim-treesitter` way is already used for folds and somewhat well-maintained. On the other hand, the second way seems simpler.

I think that, in general, a language parser shouldn't be runtime/framework-specific, but should be abstract. A library or package of that language could recognize a range between some nodes, which is not a node itself, as a _context_ (`glBegin() ... glEnd()` in C), and the user should be able to write a query that represents this logic. This plugin has already forced at least one parser maintainer to change the grammar. The opposite should happen: the diversity of languages, libraries and frameworks should cause the tools around them to improve support more complicated logic.
