### ISSUE TITLE
support a line separate like context.vim 

### ISSUE THREAD

**Issue by zdmgmail** [nvim-treesitter/nvim-treesitter-context#55]
please support draw a line to separate context like context.vim  , then don't need different highlight TreesitterContext may be look better

**Comment by romgrk** [comment]
Not enough bandwidth to implement, PR welcome

**Comment by solarizedalias** [comment]
Not as great as `context.vim` (no indent or lable) but this patch adds the minimal support.
If you think this is worth a PR, please let me know.

You can set the character with `require'treesitter-context'.setup { separator = 'x' }`.  Setting this with a single space would be interesting if you want a blank line.

In short, this is rendered as the border of the lower end of the display window.
Since the element of `config.border` to pass `nvim_open_win()` must be one character long, we cannot support more complex separator like `context.vim` this way.

With this patch, it looks like this.
<img width="547" alt="Screen Shot 2021-11-22 at 19 45 38" src="https://user-images.githubusercontent.com/60473183/142847961-e74bb08d-2bc0-4a2a-aa04-4ab334e43f33.png">


```patch
diff --git a/lua/treesitter-context.lua b/lua/treesitter-context.lua
index 595d627..2524c7d 100644
--- a/lua/treesitter-context.lua
+++ b/lua/treesitter-context.lua
@@ -218,6 +218,8 @@ do
 end
 
 local function display_window(width, height, row, col)
+  local sep = config.separator or '┄'
+  local border = {'', '', '', '', sep, sep, sep, ''}
   if winid == nil or not api.nvim_win_is_valid(winid) then
     winid = api.nvim_open_win(bufnr, false, {
       relative = 'win',
@@ -228,6 +230,7 @@ local function display_window(width, height, row, col)
       focusable = false,
       style = 'minimal',
       noautocmd = true,
+      border = border,
     })
     api.nvim_win_set_var(winid, 'treesitter_context', true)
   else
@@ -238,6 +241,7 @@ local function display_window(width, height, row, col)
       height = height,
       row = row,
       col = col,
+      border = border,
     })
   end
   api.nvim_win_set_option(winid, 'winhl', 'NormalFloat:TreesitterContext')
```
